"""create_customer_projects_and_related_tables

Revision ID: eb6dd0b7a87b
Revises: p5q6r7s8t9u0
Create Date: 2026-06-18 18:56:10.941325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb6dd0b7a87b'
down_revision: Union[str, None] = 'p5q6r7s8t9u0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('company_scale', sa.String(), nullable=True),
    sa.Column('business_model', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.JSON(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'DIAGNOSING', 'DESIGNING', 'READY', 'ARCHIVED', name='customerprojectstatus'), nullable=True),
    sa.Column('diagnosis', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('salary_monthly', sa.Float(), nullable=True),
    sa.Column('salary_annual', sa.Float(), nullable=True),
    sa.Column('salary_structure', sa.Text(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('report_to', sa.String(), nullable=True),
    sa.Column('work_location', sa.String(), nullable=True),
    sa.Column('work_hours', sa.String(), nullable=True),
    sa.Column('probation_months', sa.Integer(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('bonus', sa.Text(), nullable=True),
    sa.Column('special_terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valid_days', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', 'BLOCKED', name='projecttaskstatus'), nullable=True),
    sa.Column('assignee_type', sa.String(), nullable=True),
    sa.Column('ai_employee_type', sa.String(), nullable=True),
    sa.Column('linked_capability_sample_ids', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['customer_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solution_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['customer_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('ai_employee_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('employee_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACCEPTED', 'DISCARDED', name='aiemployeerunstatus'), nullable=True),
    sa.Column('prompt_context', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('reviewer_decision', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coding_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_type', sa.String(length=20), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('test_cases', sa.JSON(), nullable=True),
    sa.Column('time_limit_ms', sa.Integer(), nullable=True),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=True),
    sa.Column('public_token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='codingteststatus'), nullable=True),
    sa.Column('question_bank_id', sa.UUID(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('question_generation_status', sa.String(length=20), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_banks.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_tests_public_token'), 'coding_tests', ['public_token'], unique=True)
    op.create_table('knowledge_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_file_path', sa.String(), nullable=True),
    sa.Column('source_resume_id', sa.UUID(), nullable=True),
    sa.Column('source_confidentiality', sa.String(), nullable=True),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('chunk_total', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_section', sa.String(), nullable=True),
    sa.Column('source_locator', sa.String(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('retrieval_metadata', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('industry_tags', sa.JSON(), nullable=True),
    sa.Column('business_topic_tags', sa.JSON(), nullable=True),
    sa.Column('scenario_tags', sa.JSON(), nullable=True),
    sa.Column('evidence_type_tags', sa.JSON(), nullable=True),
    sa.Column('capability_tags', sa.JSON(), nullable=True),
    sa.Column('methodology_tags', sa.JSON(), nullable=True),
    sa.Column('customer_type_tags', sa.JSON(), nullable=True),
    sa.Column('value_tags', sa.JSON(), nullable=True),
    sa.Column('proves', sa.JSON(), nullable=True),
    sa.Column('does_not_prove', sa.JSON(), nullable=True),
    sa.Column('applicable_conditions', sa.JSON(), nullable=True),
    sa.Column('migration_risks', sa.JSON(), nullable=True),
    sa.Column('evidence_strength_score', sa.Float(), nullable=True),
    sa.Column('data_verification_score', sa.Float(), nullable=True),
    sa.Column('commercial_value_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('manual_review_status', sa.Enum('UNREVIEWED', 'REVIEWED', 'NEEDS_REVISION', name='knowledgeassetreviewstatus'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_assets_source_document_id'), 'knowledge_assets', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_assets_source_resume_id'), 'knowledge_assets', ['source_resume_id'], unique=False)
    op.create_index(op.f('ix_knowledge_assets_source_type'), 'knowledge_assets', ['source_type'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('candidate_name', sa.String(), nullable=False),
    sa.Column('candidate_email', sa.String(), nullable=False),
    sa.Column('salary_monthly', sa.Float(), nullable=True),
    sa.Column('salary_annual', sa.Float(), nullable=True),
    sa.Column('salary_structure', sa.Text(), nullable=True),
    sa.Column('position_title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('report_to', sa.String(), nullable=True),
    sa.Column('work_location', sa.String(), nullable=True),
    sa.Column('work_hours', sa.String(), nullable=True),
    sa.Column('onboard_date', sa.DateTime(), nullable=True),
    sa.Column('probation_months', sa.Integer(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('bonus', sa.Text(), nullable=True),
    sa.Column('special_terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'WITHDRAWN', name='offerstatus'), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('coding_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coding_test_id', sa.UUID(), nullable=True),
    sa.Column('candidate_name', sa.String(), nullable=True),
    sa.Column('candidate_email', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('run_result', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('ai_evaluation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'EVALUATED', name='codingsubmissionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coding_test_id'], ['coding_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('department_reviews', 'recommendation',
               existing_type=postgresql.ENUM('recommend', 'not_recommend', 'pending', name='reviewrecommendation'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('department_reviews', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('department_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_department_reviews_resume_id', table_name='department_reviews')
    op.drop_index('ix_department_reviews_reviewer_id', table_name='department_reviews')
    op.drop_constraint('department_reviews_resume_id_fkey', 'department_reviews', type_='foreignkey')
    op.drop_constraint('department_reviews_reviewer_id_fkey', 'department_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'department_reviews', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'department_reviews', 'users', ['reviewer_id'], ['id'])
    op.alter_column('resumes', 'parse_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'processing'::character varying"))
    op.drop_constraint('fk_resumes_rejected_by', 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['rejected_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key('fk_resumes_rejected_by', 'resumes', 'users', ['rejected_by'], ['id'], ondelete='SET NULL')
    op.alter_column('resumes', 'parse_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'processing'::character varying"))
    op.drop_constraint(None, 'department_reviews', type_='foreignkey')
    op.drop_constraint(None, 'department_reviews', type_='foreignkey')
    op.create_foreign_key('department_reviews_reviewer_id_fkey', 'department_reviews', 'users', ['reviewer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('department_reviews_resume_id_fkey', 'department_reviews', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_department_reviews_reviewer_id', 'department_reviews', ['reviewer_id'], unique=False)
    op.create_index('ix_department_reviews_resume_id', 'department_reviews', ['resume_id'], unique=False)
    op.alter_column('department_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('department_reviews', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('department_reviews', 'recommendation',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('recommend', 'not_recommend', 'pending', name='reviewrecommendation'),
               existing_nullable=True)
    op.drop_table('coding_submissions')
    op.drop_table('offers')
    op.drop_index(op.f('ix_knowledge_assets_source_type'), table_name='knowledge_assets')
    op.drop_index(op.f('ix_knowledge_assets_source_resume_id'), table_name='knowledge_assets')
    op.drop_index(op.f('ix_knowledge_assets_source_document_id'), table_name='knowledge_assets')
    op.drop_table('knowledge_assets')
    op.drop_index(op.f('ix_coding_tests_public_token'), table_name='coding_tests')
    op.drop_table('coding_tests')
    op.drop_table('ai_employee_runs')
    op.drop_table('solution_documents')
    op.drop_table('project_tasks')
    op.drop_table('offer_templates')
    op.drop_table('customer_projects')
    # ### end Alembic commands ###
